# Generated by Django 3.2.4 on 2023-07-24 06:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_alter_project_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('path', models.TextField(max_length=500)),
                ('size', models.CharField(max_length=255)),
                ('datetime_latest', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
