# Generated by Django 3.2.4 on 2023-08-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='description',
            field=models.TextField(default='none'),
        ),
    ]
