# Generated by Django 3.2.4 on 2023-08-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0002_alter_useractivitylog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='resubmit',
            field=models.BooleanField(default=False),
        ),
    ]
