# Generated by Django 3.2.4 on 2023-08-16 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0003_useractivitylog_resubmit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivitylog',
            name='resubmit',
        ),
    ]
