# Generated by Django 3.2.4 on 2023-07-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('diseaseName', models.CharField(max_length=500)),
                ('buildversion', models.CharField(max_length=500)),
                ('inputtype', models.CharField(max_length=500)),
                ('input', models.CharField(max_length=500)),
                ('ref_raw', models.CharField(max_length=500)),
                ('mafvalue', models.FloatField(max_length=500)),
                ('genovalue', models.FloatField(max_length=500)),
                ('hewvalue', models.FloatField(max_length=500)),
                ('infoscore', models.FloatField(max_length=500)),
            ],
        ),
    ]
