# Generated by Django 3.2.4 on 2023-07-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='diseaseName',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
