# Generated by Django 3.2.4 on 2023-08-08 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='Nextflow',
        ),
    ]
