# Generated by Django 3.2.4 on 2023-08-09 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_status_nextflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextflowProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Queueing', max_length=500)),
                ('progress', models.CharField(default='0%', max_length=500)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.DeleteModel(
            name='Nextflow',
        ),
    ]
