# Generated by Django 3.2.4 on 2023-08-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20230809_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='genovalue',
            field=models.FloatField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='hewvalue',
            field=models.FloatField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='infoscore',
            field=models.FloatField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='mafvalue',
            field=models.FloatField(blank=True, max_length=500, null=True),
        ),
    ]
