# Generated by Django 3.2.4 on 2023-07-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=500)),
                ('lastname', models.CharField(max_length=500)),
                ('email', models.EmailField(default='none', max_length=500)),
                ('role', models.CharField(default='user', max_length=500)),
                ('organization', models.CharField(default='none', max_length=500)),
                ('approval', models.CharField(default='pending', max_length=500)),
            ],
        ),
    ]
